/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import bean.UsuarioMr;
import dao.UsuariosDAO;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import query.JDLgConsultasFuncionarios;
import query.JDLgConsultasVendas;
import query.JDLgConsultasAnimal;
import query.JDLgConsultasClientes;
import query.JDLgConsultasUsuario;
import view.tools.Util;
/**
 *
 * @author u04127224290
 */
public class JFrmPrincipal extends javax.swing.JFrame {

  

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Sistema de Compra e Venda");
        setExtendedState(MAXIMIZED_BOTH);
         JFrmLogim JFrmLogim = new JFrmLogim();
            JFrmLogim.dispose();
       
        
    }

  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jMmuUsuario = new javax.swing.JButton();
        jMmuAnimais = new javax.swing.JButton();
        jMmuVenda = new javax.swing.JButton();
        jMmuConsutasUsua = new javax.swing.JButton();
        BTnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMmuSair = new javax.swing.JMenu();
        jMmuUsuarios = new javax.swing.JMenuItem();
        jMmuClientes = new javax.swing.JMenuItem();
        jMmuFuncionarios = new javax.swing.JMenuItem();
        jMmuProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMmuSairr = new javax.swing.JMenuItem();
        jMmuCompras_Vendas = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMmuConsutaUsu = new javax.swing.JMenu();
        jMnuConsutaUsu = new javax.swing.JMenuItem();
        jMnuConsutaFun = new javax.swing.JMenuItem();
        jMnuConsutaCli = new javax.swing.JMenuItem();
        jMnuConsutaAni = new javax.swing.JMenuItem();
        jMnuConsutaVen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMmuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMmuUsuario.setText("Usuarios");
        jMmuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMmuUsuario.setDisabledIcon(null);
        jMmuUsuario.setFocusable(false);
        jMmuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMmuUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMmuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarioActionPerformed(evt);
            }
        });
        jMmuUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMmuUsuarioKeyPressed(evt);
            }
        });
        jToolBar1.add(jMmuUsuario);

        jMmuAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-animal-48.png"))); // NOI18N
        jMmuAnimais.setText("Animais");
        jMmuAnimais.setToolTipText("");
        jMmuAnimais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMmuAnimais.setDisabledIcon(null);
        jMmuAnimais.setFocusable(false);
        jMmuAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMmuAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMmuAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuAnimaisActionPerformed(evt);
            }
        });
        jToolBar1.add(jMmuAnimais);

        jMmuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stats_pie_chart.png"))); // NOI18N
        jMmuVenda.setText("Vendas");
        jMmuVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMmuVenda.setDisabledIcon(null);
        jMmuVenda.setFocusable(false);
        jMmuVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMmuVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMmuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(jMmuVenda);

        jMmuConsutasUsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta/icons8-usuário-homem-com-círculo-64.png"))); // NOI18N
        jMmuConsutasUsua.setText("Consutar Usuario");
        jMmuConsutasUsua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMmuConsutasUsua.setDisabledIcon(null);
        jMmuConsutasUsua.setFocusable(false);
        jMmuConsutasUsua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMmuConsutasUsua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMmuConsutasUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuConsutasUsuaActionPerformed(evt);
            }
        });
        jToolBar1.add(jMmuConsutasUsua);

        BTnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        BTnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTnSairActionPerformed(evt);
            }
        });

        jMmuSair.setMnemonic('C');
        jMmuSair.setText("Cadastros");
        jMmuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuSairActionPerformed(evt);
            }
        });

        jMmuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMmuUsuarios.setMnemonic('u');
        jMmuUsuarios.setText("Usuarios");
        jMmuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuariosActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuUsuarios);

        jMmuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMmuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMmuClientes.setMnemonic('c');
        jMmuClientes.setText("Clientes");
        jMmuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuClientesActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuClientes);

        jMmuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMmuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/client_user.png"))); // NOI18N
        jMmuFuncionarios.setMnemonic('f');
        jMmuFuncionarios.setText("Funcionario");
        jMmuFuncionarios.setMaximumSize(new java.awt.Dimension(32667, 32767));
        jMmuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuFuncionariosActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuFuncionarios);

        jMmuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMmuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMmuProduto.setMnemonic('p');
        jMmuProduto.setText("Animais");
        jMmuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuProdutoActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuProduto);
        jMmuSair.add(jSeparator1);

        jMmuSairr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMmuSairr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMmuSairr.setMnemonic('s');
        jMmuSairr.setText("Sair");
        jMmuSairr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuSairrActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuSairr);

        jMenuBar1.add(jMmuSair);

        jMmuCompras_Vendas.setMnemonic('m');
        jMmuCompras_Vendas.setText("Movimentos");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stats_pie_chart.png"))); // NOI18N
        jMnuVendas.setText("vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMmuCompras_Vendas.add(jMnuVendas);

        jMenuBar1.add(jMmuCompras_Vendas);

        jMmuConsutaUsu.setMnemonic('m');
        jMmuConsutaUsu.setText("Consutas");
        jMmuConsutaUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMnuConsutaUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsutaUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta/icons8-usuário-homem-com-círculo-64.png"))); // NOI18N
        jMnuConsutaUsu.setText("Consutar Usuario");
        jMnuConsutaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsutaUsuActionPerformed(evt);
            }
        });
        jMmuConsutaUsu.add(jMnuConsutaUsu);

        jMnuConsutaFun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsutaFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta/icons8-crachá-48.png"))); // NOI18N
        jMnuConsutaFun.setText("Consutar Funcionario");
        jMnuConsutaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsutaFunActionPerformed(evt);
            }
        });
        jMmuConsutaUsu.add(jMnuConsutaFun);

        jMnuConsutaCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsutaCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta/icons8-orçamento-48.png"))); // NOI18N
        jMnuConsutaCli.setText("Consutar Clientes");
        jMnuConsutaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsutaCliActionPerformed(evt);
            }
        });
        jMmuConsutaUsu.add(jMnuConsutaCli);

        jMnuConsutaAni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsutaAni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta/icons8-grupo-de-animais-50.png"))); // NOI18N
        jMnuConsutaAni.setText("Consutar Animais");
        jMnuConsutaAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsutaAniActionPerformed(evt);
            }
        });
        jMmuConsutaUsu.add(jMnuConsutaAni);

        jMnuConsutaVen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsutaVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta/icons8-sacar-dinheiro-50.png"))); // NOI18N
        jMnuConsutaVen.setText("Consutar Vendas");
        jMnuConsutaVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsutaVenActionPerformed(evt);
            }
        });
        jMmuConsutaUsu.add(jMnuConsutaVen);

        jMenuBar1.add(jMmuConsutaUsu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTnSair))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(BTnSair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMmuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuVendaActionPerformed
        // TODO add your handling code here:
         JDLgVendas JDLgVendas = new JDLgVendas(this, true);
                JDLgVendas.setVisible(true);
    }//GEN-LAST:event_jMmuVendaActionPerformed

    private void jMmuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
                jDlgUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jMmuUsuarioActionPerformed

    private void jMmuAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuAnimaisActionPerformed
JDlgAnimaisNovo JDlgAnimais = new JDlgAnimaisNovo(this, true);
                JDlgAnimais.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuAnimaisActionPerformed

    private void BTnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTnSairActionPerformed
        if( Util.perguntar("Sair", "Deseja fechar o programa?") == YES_NO_OPTION){
            
     System.exit(0);
      }
    }//GEN-LAST:event_BTnSairActionPerformed

    private void jMmuUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMmuUsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuUsuarioKeyPressed

    private void jMmuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setVisible(true);

    }//GEN-LAST:event_jMmuUsuariosActionPerformed

    private void jMmuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuClientesActionPerformed
        // TODO add your handling code here:
        JDlgCliente JDlgCliente = new JDlgCliente(this, true);
        JDlgCliente.setVisible(true);
    }//GEN-LAST:event_jMmuClientesActionPerformed

    private void jMmuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuFuncionariosActionPerformed
        JDlgFuncionarioNovo JDlgFuncionario = new JDlgFuncionarioNovo(this, true);
        JDlgFuncionario.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jMmuFuncionariosActionPerformed

    private void jMmuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuProdutoActionPerformed

        JDlgAnimaisNovo JDlgAnimais = new JDlgAnimaisNovo(this, true);
        JDlgAnimais.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuProdutoActionPerformed

    private void jMmuSairrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuSairrActionPerformed
        // TODO add your handling code here:
         if( Util.perguntar("Sair", "Deseja fechar o programa?") == YES_NO_OPTION){
            
     System.exit(0);
      }
    }//GEN-LAST:event_jMmuSairrActionPerformed

    private void jMmuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuSairActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMmuSairActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
        JDLgVendas JDLgVendas = new JDLgVendas(this, true);
        JDLgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuConsutaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsutaUsuActionPerformed
   query.JDLgConsultasUsuario consutas = new JDLgConsultasUsuario(this, true);
                consutas.setVisible(true);    }//GEN-LAST:event_jMnuConsutaUsuActionPerformed

    private void jMnuConsutaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsutaFunActionPerformed
        query.JDLgConsultasFuncionarios consutas = new JDLgConsultasFuncionarios(this, true);
                consutas.setVisible(true);
    }//GEN-LAST:event_jMnuConsutaFunActionPerformed

    private void jMnuConsutaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsutaCliActionPerformed
 query.JDLgConsultasClientes consutas = new JDLgConsultasClientes(this, true);
                consutas.setVisible(true);    }//GEN-LAST:event_jMnuConsutaCliActionPerformed

    private void jMnuConsutaAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsutaAniActionPerformed
query.JDLgConsultasAnimal consutas = new JDLgConsultasAnimal(this, true);
                consutas.setVisible(true);    }//GEN-LAST:event_jMnuConsutaAniActionPerformed

    private void jMnuConsutaVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsutaVenActionPerformed
query.JDLgConsultasVendas consutas = new JDLgConsultasVendas(this, true);
                consutas.setVisible(true);    }//GEN-LAST:event_jMnuConsutaVenActionPerformed

    private void jMmuConsutasUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuConsutasUsuaActionPerformed
  query.JDLgConsultasUsuario consutas = new JDLgConsultasUsuario(this, true);
                consutas.setVisible(true);    }//GEN-LAST:event_jMmuConsutasUsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
              JFrmLogim JFrmLogim = new JFrmLogim();
           JFrmLogim.setVisible(true) ;
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTnSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jMmuAnimais;
    private javax.swing.JMenuItem jMmuClientes;
    private javax.swing.JMenu jMmuCompras_Vendas;
    private javax.swing.JMenu jMmuConsutaUsu;
    private javax.swing.JButton jMmuConsutasUsua;
    private javax.swing.JMenuItem jMmuFuncionarios;
    private javax.swing.JMenuItem jMmuProduto;
    private javax.swing.JMenu jMmuSair;
    private javax.swing.JMenuItem jMmuSairr;
    private javax.swing.JButton jMmuUsuario;
    private javax.swing.JMenuItem jMmuUsuarios;
    private javax.swing.JButton jMmuVenda;
    private javax.swing.JMenuItem jMnuConsutaAni;
    private javax.swing.JMenuItem jMnuConsutaCli;
    private javax.swing.JMenuItem jMnuConsutaFun;
    private javax.swing.JMenuItem jMnuConsutaUsu;
    private javax.swing.JMenuItem jMnuConsutaVen;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
