package bean;
// Generated 21/09/2023 15:04:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClienteMr generated by hbm2java
 */
@Entity
@Table(name="cliente_mr"
    ,catalog="db_maycon_borges"
)
public class ClienteMr  implements java.io.Serializable {


     private int idClienteMr;
     private UsuarioMr usuarioMr;
     private String nomeMr;
     private String emailMr;
     private String cepMr;
     private String rgMr;

    public ClienteMr() {
    }

	
    public ClienteMr(int idClienteMr, UsuarioMr usuarioMr, String nomeMr, String emailMr, String cepMr, String rgMr) {
        this.idClienteMr = idClienteMr;
        this.usuarioMr = usuarioMr;
        this.nomeMr = nomeMr;
        this.emailMr = emailMr;
        this.cepMr = cepMr;
        this.rgMr = rgMr;
    }
    public ClienteMr( UsuarioMr usuarioMr, String nomeMr, String emailMr, String cepMr, String rgMr, int idClienteMr) {
       this.idClienteMr = idClienteMr;
       this.usuarioMr = usuarioMr;
       this.nomeMr = nomeMr;
       this.emailMr = emailMr;
       this.cepMr = cepMr;
       this.rgMr = rgMr;
    }
   
     @Id 

    
    @Column(name="idCliente_MR", unique=true, nullable=false)
    public int getIdClienteMr() {
        return this.idClienteMr;
    }
    
    public void setIdClienteMr(int idClienteMr) {
        this.idClienteMr = idClienteMr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario_MR", nullable=false)
    public UsuarioMr getUsuarioMr() {
        return this.usuarioMr;
    }
    
    public void setUsuarioMr(UsuarioMr usuarioMr) {
        this.usuarioMr = usuarioMr;
    }

    
    @Column(name="Nome_MR", nullable=false, length=60)
    public String getNomeMr() {
        return this.nomeMr;
    }
    
    public void setNomeMr(String nomeMr) {
        this.nomeMr = nomeMr;
    }

    
    @Column(name="Email_MR", nullable=false, length=50)
    public String getEmailMr() {
        return this.emailMr;
    }
    
    public void setEmailMr(String emailMr) {
        this.emailMr = emailMr;
    }

    
    @Column(name="Cep_MR", nullable=false, length=15)
    public String getCepMr() {
        return this.cepMr;
    }
    
    public void setCepMr(String cepMr) {
        this.cepMr = cepMr;
    }

    
    @Column(name="Rg_MR", nullable=false, length=15)
    public String getRgMr() {
        return this.rgMr;
    }
    
    public void setRgMr(String rgMr) {
        this.rgMr = rgMr;
    }

@Override
      public String toString(){
          return getNomeMr();
          
}



}


