package bean;
// Generated 01/12/2023 14:49:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FunionarioMr generated by hbm2java
 */
@Entity
@Table(name="funionario_mr"
    ,catalog="db_maycon_borges"
)
public class FunionarioMr  implements java.io.Serializable {


     private int idFunionarioMr;
     private UsuarioMr usuarioMr;
     private String nomeMr;
     private int sexoMr;
     private String emailMr;
     private String numeroTelMr;

    public FunionarioMr() {
    }

	
    public FunionarioMr(int idFunionarioMr, UsuarioMr usuarioMr, String nomeMr, int sexoMr, String emailMr, String numeroTelMr) {
        this.idFunionarioMr = idFunionarioMr;
        this.usuarioMr = usuarioMr;
        this.nomeMr = nomeMr;
        this.sexoMr = sexoMr;
        this.emailMr = emailMr;
        this.numeroTelMr = numeroTelMr;
    }
    public FunionarioMr(int idFunionarioMr, UsuarioMr usuarioMr, String nomeMr , String numeroTelMr, String emailMr , int sexoMr) {
       this.idFunionarioMr = idFunionarioMr;
       this.usuarioMr = usuarioMr;
       this.nomeMr = nomeMr;
       this.sexoMr = sexoMr;
       this.emailMr = emailMr;
       this.numeroTelMr = numeroTelMr;
    }
   
     @Id 

    
    @Column(name="idFunionario_MR", unique=true, nullable=false)
    public int getIdFunionarioMr() {
        return this.idFunionarioMr;
    }
    
    public void setIdFunionarioMr(int idFunionarioMr) {
        this.idFunionarioMr = idFunionarioMr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario_MR", nullable=false)
    public UsuarioMr getUsuarioMr() {
        return this.usuarioMr;
    }
    
    public void setUsuarioMr(UsuarioMr usuarioMr) {
        this.usuarioMr = usuarioMr;
    }

    
    @Column(name="Nome_MR", nullable=false, length=60)
    public String getNomeMr() {
        return this.nomeMr;
    }
    
    public void setNomeMr(String nomeMr) {
        this.nomeMr = nomeMr;
    }

    
    @Column(name="Sexo_MR", nullable=false)
    public int getSexoMr() {
        return this.sexoMr;
    }
    
    public void setSexoMr(int sexoMr) {
        this.sexoMr = sexoMr;
    }

    
    @Column(name="email_MR", nullable=false, length=60)
    public String getEmailMr() {
        return this.emailMr;
    }
    
    public void setEmailMr(String emailMr) {
        this.emailMr = emailMr;
    }

    
    @Column(name="Numero_tel_MR", nullable=false, length=13)
    public String getNumeroTelMr() {
        return this.numeroTelMr;
    }
    
    public void setNumeroTelMr(String numeroTelMr) {
        this.numeroTelMr = numeroTelMr;
    }


  @Override
     public String toString() {
return this.nomeMr;
}
@Override
public boolean equals(Object object) {
if (object instanceof FunionarioMr) {
FunionarioMr atu = (FunionarioMr) object;
if (this.getIdFunionarioMr()== atu.getIdFunionarioMr()) {
return true;
}
}
return false;
}

}


