package bean;
// Generated 09/11/2023 15:03:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendasAnimaisMrId generated by hbm2java
 */
@Embeddable
public class VendasAnimaisMrId  implements java.io.Serializable {


     private int vendasIdVendasMr;
     private int animaisIdAnimaisMr;
     private int idVendasAnimaisMr;

    public VendasAnimaisMrId() {
    }

    public VendasAnimaisMrId(int vendasIdVendasMr, int animaisIdAnimaisMr, int idVendasAnimaisMr) {
       this.vendasIdVendasMr = vendasIdVendasMr;
       this.animaisIdAnimaisMr = animaisIdAnimaisMr;
       this.idVendasAnimaisMr = idVendasAnimaisMr;
    }
   


    @Column(name="Vendas_idVendas_MR", nullable=false)
    public int getVendasIdVendasMr() {
        return this.vendasIdVendasMr;
    }
    
    public void setVendasIdVendasMr(int vendasIdVendasMr) {
        this.vendasIdVendasMr = vendasIdVendasMr;
    }


    @Column(name="Animais_idAnimais_MR", nullable=false)
    public int getAnimaisIdAnimaisMr() {
        return this.animaisIdAnimaisMr;
    }
    
    public void setAnimaisIdAnimaisMr(int animaisIdAnimaisMr) {
        this.animaisIdAnimaisMr = animaisIdAnimaisMr;
    }


    @Column(name="IdVendas_Animais_MR", unique=true, nullable=false)
    public int getIdVendasAnimaisMr() {
        return this.idVendasAnimaisMr;
    }
    
    public void setIdVendasAnimaisMr(int idVendasAnimaisMr) {
        this.idVendasAnimaisMr = idVendasAnimaisMr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendasAnimaisMrId) ) return false;
		 VendasAnimaisMrId castOther = ( VendasAnimaisMrId ) other; 
         
		 return (this.getVendasIdVendasMr()==castOther.getVendasIdVendasMr())
 && (this.getAnimaisIdAnimaisMr()==castOther.getAnimaisIdAnimaisMr())
 && (this.getIdVendasAnimaisMr()==castOther.getIdVendasAnimaisMr());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVendasIdVendasMr();
         result = 37 * result + this.getAnimaisIdAnimaisMr();
         result = 37 * result + this.getIdVendasAnimaisMr();
         return result;
   }   


}


