package bean;
// Generated 14/09/2023 14:18:15 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VendasAnimaisMr generated by hbm2java
 */
@Entity
@Table(name="vendas_animais_mr"
    ,catalog="db_maycon_borges"
    , uniqueConstraints = @UniqueConstraint(columnNames="IdVendas_Animais_MR") 
)
public class VendasAnimaisMr  implements java.io.Serializable {


     private VendasAnimaisMrId id;
     private AnimaisMr animaisMr;
     private VendasMr vendasMr;
     private int quantidadeUnitariaMr;
     private String valorUnitarioMr;

    public VendasAnimaisMr() {
    }

    public VendasAnimaisMr(VendasAnimaisMrId id, AnimaisMr animaisMr, VendasMr vendasMr, int quantidadeUnitariaMr, String valorUnitarioMr) {
       this.id = id;
       this.animaisMr = animaisMr;
       this.vendasMr = vendasMr;
       this.quantidadeUnitariaMr = quantidadeUnitariaMr;
       this.valorUnitarioMr = valorUnitarioMr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vendasIdVendasMr", column=@Column(name="Vendas_idVendas_MR", nullable=false) ), 
        @AttributeOverride(name="animaisIdAnimaisMr", column=@Column(name="Animais_idAnimais_MR", nullable=false) ), 
        @AttributeOverride(name="idVendasAnimaisMr", column=@Column(name="IdVendas_Animais_MR", unique=true, nullable=false) ) } )
    public VendasAnimaisMrId getId() {
        return this.id;
    }
    
    public void setId(VendasAnimaisMrId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Animais_idAnimais_MR", nullable=false, insertable=false, updatable=false)
    public AnimaisMr getAnimaisMr() {
        return this.animaisMr;
    }
    
    public void setAnimaisMr(AnimaisMr animaisMr) {
        this.animaisMr = animaisMr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendas_idVendas_MR", nullable=false, insertable=false, updatable=false)
    public VendasMr getVendasMr() {
        return this.vendasMr;
    }
    
    public void setVendasMr(VendasMr vendasMr) {
        this.vendasMr = vendasMr;
    }

    
    @Column(name="Quantidade_Unitaria_MR", nullable=false)
    public int getQuantidadeUnitariaMr() {
        return this.quantidadeUnitariaMr;
    }
    
    public void setQuantidadeUnitariaMr(int quantidadeUnitariaMr) {
        this.quantidadeUnitariaMr = quantidadeUnitariaMr;
    }

    
    @Column(name="Valor_unitario_MR", nullable=false, length=100)
    public String getValorUnitarioMr() {
        return this.valorUnitarioMr;
    }
    
    public void setValorUnitarioMr(String valorUnitarioMr) {
        this.valorUnitarioMr = valorUnitarioMr;
    }




}


