package bean;
// Generated 01/12/2023 14:49:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasAnimaisMr generated by hbm2java
 */
@Entity
@Table(name="vendas_animais_mr"
    ,catalog="db_maycon_borges"
)
public class VendasAnimaisMr  implements java.io.Serializable {


     private Integer idVendasAnimaisMr;
     private AnimaisMr animaisMr;
     private VendasMr vendasMr;
     private int quantidadeUnitariaMr;
     private double valorUnitarioMr;

    public VendasAnimaisMr() {
    }

    public VendasAnimaisMr(AnimaisMr animaisMr, VendasMr vendasMr, int quantidadeUnitariaMr, double valorUnitarioMr) {
       this.animaisMr = animaisMr;
       this.vendasMr = vendasMr;
       this.quantidadeUnitariaMr = quantidadeUnitariaMr;
       this.valorUnitarioMr = valorUnitarioMr;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdVendas_Animais_MR", unique=true, nullable=false)
    public Integer getIdVendasAnimaisMr() {
        return this.idVendasAnimaisMr;
    }
    
    public void setIdVendasAnimaisMr(Integer idVendasAnimaisMr) {
        this.idVendasAnimaisMr = idVendasAnimaisMr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Animais_idAnimais_MR", nullable=false)
    public AnimaisMr getAnimaisMr() {
        return this.animaisMr;
    }
    
    public void setAnimaisMr(AnimaisMr animaisMr) {
        this.animaisMr = animaisMr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendas_idVendas_MR", nullable=false)
    public VendasMr getVendasMr() {
        return this.vendasMr;
    }
    
    public void setVendasMr(VendasMr vendasMr) {
        this.vendasMr = vendasMr;
    }

    
    @Column(name="Quantidade_Unitaria_MR", nullable=false)
    public int getQuantidadeUnitariaMr() {
        return this.quantidadeUnitariaMr;
    }
    
    public void setQuantidadeUnitariaMr(int quantidadeUnitariaMr) {
        this.quantidadeUnitariaMr = quantidadeUnitariaMr;
    }

    
    @Column(name="Valor_unitario_MR", nullable=false, precision=12)
    public double getValorUnitarioMr() {
        return this.valorUnitarioMr;
    }
    
    public void setValorUnitarioMr(double valorUnitarioMr) {
        this.valorUnitarioMr = valorUnitarioMr;
    }




}


